bev_features_folder_train: '/workspace/BLIP/data_thesis/bev_features_t/train'
bev_features_folder_val: '/workspace/BLIP/data_thesis/bev_features_t/val'
drivelm_jsons: ['/workspace/BLIP/data_thesis/QA_dataset_nus/v1_1_train_nus.json']

batch_size: 10

# optimizer
weight_decay: 0.05
init_lr: 0.000005
min_lr: 0.000001
lr_decay_rate: 0.9
max_epoch: 10
