bev_features_folder_train: '/workspace/thesis/data_thesis/bev_features_t/train/'
bev_features_folder_val: '/workspace/thesis/data_thesis/bev_features_t/val/'
drivelm_jsons: '/workspace/thesis/data_thesis/QA_dataset_nus/v1_1_train_nus.json'

train: '/workspace/thesis/data_thesis/QA_dataset_nus/train.json'
val: '/workspace/thesis/data_thesis/QA_dataset_nus/val.json'

batch_size: 10

# optimizer
weight_decay: 0.05
init_lr: 0.000005
min_lr: 0.0000005
lr_decay_rate: 0.9
max_epoch: 10
